version: '2.1'

services:
  mysql-master:
    image: 'bitnami/mysql:latest'
    hostname: mysql-master
    ports:
      - '3306'
    volumes:
      - ./mysql-persistence/data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
  mysql-rslave:
    image: 'bitnami/mysql:latest'
    hostname: mysql-rslave
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password

  mysql-bslave:
    image: 'bitnami/mysql:latest'
    hostname: mysql-bslave
    ports:
      - '3306'
    volumes:
      - ./conf/mysql/create-orcuser.sh:/tmp/create-orcuser.sh
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
    healthcheck:
      test: ['CMD', 'sh /tmp/create-orcuser.sh']
      interval: 15s
      timeout: 5s
      retries: 0
  proxysql:
    image: proxysql/proxysql:latest
    ports:
      - "16033:6033"
      - "16032:6032"
    volumes:
      - ./conf/proxysql/proxysql.cnf:/etc/proxysql.cnf
    depends_on:
      - mysql-master
      - mysql-slave

  orc1:
    build: ./conf/orchestrator
    ports:
      - "23101:3000"
    volumes:
      - ./conf/orchestrator/conf/orchestrator-sample-sqlite.conf.json:/etc/orchestrator.conf.json
    depends_on:
      - mysql-master
      - mysql-slave
      - proxysql
 
volumes:
  mysql_master_data:
    driver: local
networks:
  default:
    name: mysql-ha
    external: true